# Generated by Django 5.0.3 on 2024-03-23 05:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('poids', models.FloatField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('examen', models.CharField(max_length=60)),
                ('type_examen', models.CharField(max_length=60)),
                ('date_examen', models.DateField(null=True)),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Patienconsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('poids', models.FloatField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('avis_medecin', models.TextField(null=True)),
                ('examen', models.CharField(max_length=50, null=True)),
                ('sevice', models.CharField(max_length=50)),
                ('date_consultation', models.DateField()),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Patienhosp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('poids', models.FloatField()),
                ('age', models.IntegerField()),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=20)),
                ('avis_medecin', models.TextField()),
                ('traitement', models.TextField()),
                ('examen', models.CharField(max_length=50)),
                ('sevice', models.CharField(max_length=50)),
                ('date_hosp', models.DateField(null=True)),
                ('date_sortie', models.DateField(null=True)),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('prix', models.IntegerField()),
                ('date_recep', models.DateField()),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_salle', models.CharField(max_length=50)),
                ('numero_salle', models.IntegerField()),
                ('nombre_lit', models.IntegerField()),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_service', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_stock', models.IntegerField()),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qte_produit', to='clinique.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte_achete', models.IntegerField()),
                ('pu', models.IntegerField(editable=False)),
                ('pttc', models.IntegerField(default=0, editable=False)),
                ('secrete_key', models.UUIDField(default=uuid.uuid4)),
                ('desigation_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qt_produit', to='clinique.produit')),
            ],
        ),
    ]
